apiVersion: v1
kind: Service
metadata:
  name: webapp11-svc
  labels:
    app: webapp1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 8080
  selector:
    app: webapp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: spring-boot-kubernetes:latest
        ports:
        - containerPort: 8080